### ISSUE TITLE
Support of API version 2018 (preview)

### ISSUE THREAD

**Issue by FMauroy** [colethecoder/chronological#13]
Hi team, great tool you're providing :)
I'm wondering if you plan to target the latest version of the API? Or maybe only when it will be released?
Cheers
fred

**Comment by colethecoder** [comment]
I have scanned the documentation and I think it would be good to support both versions but I haven't really thought through how that would work. I'm open to suggestions from users of Chronological on how it would work, I suspect bumping the version to 2.0 and allowing a few breaking changes might be a sensible approach.

**Comment by FMauroy** [comment]
Thanks for your quick reply. You could implement the new API in another namespace and keep both targets available...
So far in my tests, only the GetEnvironmentsAsync seems to work on an environment created in preview... Event and metadata queries all return 400.
