### ISSUE TITLE
If a property is bound to BuiltIn.EventTimeStamp its value isn't copied

### ISSUE THREAD

**Issue by Gimly** [colethecoder/chronological#15]
The `EventQueryResultToTypeMapper` doesn't correctly copy the value of the `BuiltIn.EventTimeStamp` built-in field to the result. Its resulting value is always `DateTime.Default`.

**Comment by martin-weber** [comment]
Same issue.

**Comment by colethecoder** [comment]
Apologies for the delayed release of this, it is now available on nuget:

https://www.nuget.org/packages/Chronological/1.0.137
