### ISSUE TITLE
Use Contains with string array

### ISSUE THREAD

**Issue by TechWatching** [colethecoder/chronological#18]
The following syntax to filter an event query works fine:
`(x => new[] { "Hello", "World"}.Contains(x.DataType)`

However if If build the array outside the filter and use it after, I have the following error:
`System.NotImplementedException: 'The method or operation is not implemented.'`
```csharp
var test = new[] { "Hello", "World"};
var events = await env.EventQuery<MyObject>(fromDate, toDate, Limit.Take, count)
                      .Where(e => test.Contains(e.DataType));
```
Is it a bug or a not supported scenario ? I am using that because my array is dynamically computed from my application settings.

**Comment by colethecoder** [comment]
I think we can consider this a bug, it seems a sensible scenario that should be supported.

I've pushed a failing test, I'll try and resolve this afternoon.

If I release a new version as beta on Nuget would you be able to test? I don't have an accessible TSI instance right now.

**Comment by TechWatching** [comment]
Okay cool. Yes sure, just tell me when you succeed to resolve that and I will test the beta package.

**Comment by colethecoder** [comment]
I'm pretty sure it is fixed, the beta package is here:

https://www.nuget.org/packages/Chronological/1.0.141-beta

If you let me know when you've tested I'll release a non-beta version.

**Comment by TechWatching** [comment]
Just tested it, it works fine with your modification. Thanks :)

**Comment by colethecoder** [comment]
Great thanks for testing I've released it properly now: 

https://www.nuget.org/packages/Chronological/1.0.141
