### ISSUE TITLE
Boolean property not correctly mapped

### ISSUE THREAD

**Issue by TechWatching** [colethecoder/chronological#19]
In my Entity class I have a boolean property :
```csharp
[ChronologicalEventField("measure.boolProperty")]
public bool IsCorrect { get; set; }
```
I can correctly use this property to filter my query in the where predicate but the property is not correctly populated with the tsi value of the corresponding boolean column.

**Comment by colethecoder** [comment]
I have a feeling that when I built the type mapping bool wasn't an option but I've checked the docs and it's there so I've added it. We don't have much test coverage for the parsing / mapping code and as with the previous issue I don't have a TSI instance available at present so if you can test and confirm this beta package works I'll then release properly.

https://www.nuget.org/packages/Chronological/1.0.142-beta

Thanks.

**Comment by TechWatching** [comment]
Your commit is exactly the correction I just had done on my fork and it worked so I am confident it will work with your beta package. I will check that and tell you.

**Comment by TechWatching** [comment]
Yep, it works fine. Thanks for the quick correction. 

And thanks for you library by the way which is really helpful while waiting for an official supported library from Microsoft. It's much better than the custom code we did to request TSI at the beginning when we did not know about Chronological.

**Comment by colethecoder** [comment]
Thanks for testing, I've released a non-beta version:

https://www.nuget.org/packages/Chronological/1.0.142
