### ISSUE TITLE
Exception on Filter class when using a variable in predicate.

### ISSUE THREAD

**Issue by Lushkin** [colethecoder/chronological#20]
![image](https://user-images.githubusercontent.com/2601842/75047329-dc082300-54c6-11ea-973e-265221f43f31.png)

The issue can be reproduced from this branch : https://github.com/Lushkin/chronological/tree/047782f98f4b51f50cd3f00b3852bf9bd97973f9

The exception is fired on line 201 of Filter.cs due to Expression.NodeType value : 
![image](https://user-images.githubusercontent.com/2601842/75047880-df4fde80-54c7-11ea-8810-6821b8372072.png)

**Comment by colethecoder** [comment]
Fixed: https://www.nuget.org/packages/Chronological/1.0.148

**Comment by Lushkin** [comment]
Great !
Thanks 😀
